feat(take): add typing
bengry/typedash pull request #7
Opened 2023-10-03 17:31 UTC by StyleShit

It's basically for fun. I've also changed the implementation a little bit, WDYT?
it probably breaks BC, I did it only for the sake of typing it :P

2023-10-05 20:39 UTC, bengry commented
> It's basically for fun. I've also changed the implementation a little bit, WDYT? it probably breaks BC, I did it only for the sake of typing it 😅

Thanks for the contribution!

The types are looking good from a quick glance, but the implementation should remain the same.
i.e. `take(array, count)` should return `[]` when `count <= 0`.
I don't believe that taking from the end is the goal of `take`.

I'd be happy to accept a `takeRight` function implementation that does this though, that's the "mirror" of `take`, if you'd like.

2023-10-06 07:38 UTC, StyleShit commented
yeah, sure, I've just reverted the logic changes.
BTW, I think you should run the CI workflows also on PRs instead of only on push, but that's for another PR.
I can open another PR for `takeLast()` / `takeRight()`, but let's first finish with this one :)

___
You should thank (or blame?) Omri Mor for the existence of this PR, he sent me this repo while I was bored 😆

2023-10-06 11:37 UTC, bengry commented
> yeah, sure, I've just reverted the logic changes

Thanks

> BTW, I think you should run the CI workflows also on PRs instead of only on push, but that's for another PR.

For sure, I'll make that change.

> Here is a [tsplay](https://tsplay.dev/wO2kEW) so you can play with it

Seems like there's a bug in the type's implementation - see `d` [here](https://tsplay.dev/WJ1vRm).

> You should thank (or blame?) Omri Mor for the existence of this PR, he sent me this repo while I was bored 😆

Will do 😂

2023-10-06 12:04 UTC, bengry requested changes
Once the outstanding comments are fixed, I think we're good to merge this :)

2023-10-06 12:04 UTC, bengry commented on src/functions/take/take.spec.ts
> +it('should remove from end for a negative count', () => {
```suggestion
it('should return an empty array for a negative count', () => {
```

2023-10-06 12:04 UTC, bengry commented on src/functions/take/take.ts
> +export function take<const T extends readonly unknown[], C extends number>(
I think the only thing I'm missing is dealing with a plain `number[]`. Seems like `Take<number[], 2>` results in `[]` instead of `number[]`.

2023-10-06 12:04 UTC, bengry commented on src/functions/take/take.ts
> +export function take<const T extends readonly unknown[], C extends number>(
Please also add a test for this, if you can.

2023-10-09 09:47 UTC, StyleShit commented on src/functions/take/take.spec.ts
> +it('should remove from end for a negative count', () => {
Oops, forgot to revert that
Done

2023-10-09 09:47 UTC, StyleShit commented on src/functions/take/take.ts
> +export function take<const T extends readonly unknown[], C extends number>(
Done

2023-10-09 10:09 UTC, bengry approved these changes
LGTM. Feel free to also open a PR for a `takeRight` function if you want to.

2023-10-09 10:10 UTC, merged